name: CI
on: [push]

env:
  ARTIFACT:   defencute
  SOURCE_DIR: ${{github.workspace}}
  QT_VERSION: 6.2.0

jobs:
    linux-gcc:
        name: Linux GCC
        runs-on: ubuntu-22.04
        env:
            CC: gcc-12
            CXX: g++-12
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install apt packages
              run: |
                  sudo apt-get update
                  sudo apt-get install -y g++-12 libstdc++-12-dev

            - name: Install Qt6
              uses: jurplel/install-qt-action@v3
              with:
                version: ${{env.QT_VERSION}}
                host:    linux
                dir:     $RUNNER_TEMP
                modules: qtscxml qt3d

            - name: Install VCPKG
              run: /bin/bash .ci/install-vcpkg.sh

            - name: Build
              run: /bin/bash .ci/build-project.sh
              env:
                QT_PATH: ${{github.workspace}}/${{env.Qt6_DIR}}


    windows-msvc:
        name: Windows MSVC
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Qt6
              uses: jurplel/install-qt-action@v3
              with:
                version: ${{env.QT_VERSION}}
                host:    windows
                dir:     $RUNNER_TEMP
                modules: qtscxml qt3d

            - name: Install VCPKG
              run: .ci\install-vcpkg.ps1

            - name: Build
              run: .ci\build-project.ps1
              env:
                QT_PATH: ${{github.workspace}}\${{env.Qt6_DIR}}

            - name: Zip build
              run:  |
                    7z a ${{runner.temp}}\${{env.ARTIFACT}} .\build\bin -r

            - name: Save build artifact
              uses: actions/upload-artifact@master
              with:
                name: ${{env.ARTIFACT}}
                path: ${{runner.temp}}\${{env.ARTIFACT}}
