name: CI
on: [push]

env:
  ARTIFACT: generated.zip

jobs:
    linux-gcc:
        name: Linux GCC
        runs-on: ubuntu-22.04
        env:
            CC: gcc-14
            CXX: g++-14
        steps:
            - uses: actions/checkout@v3
            - run: |
                  sudo apt-get update
                  sudo apt-get install -y g++-14 libstdc++-14-dev qt6-base qt6-base-dev
            - run: /bin/bash .ci/install-vcpkg.sh
            - run: /bin/bash .ci/build-project.sh

